### ISSUE TITLE
/nekocfg command does nothing, gear icon just opens /neko

### ISSUE THREAD

**Issue by Fissie96** [Meisterlala/NekoLife#2]
Title, /nekocfg gives me an error that it doesn't exist. /neko works fine.

Good plugin btw :3

**Comment by Meisterlala** [comment]
I suspect that you have version 1.0.7 installed. That is the version which is currently in the official dalamud repository.  Version 1.1.0 will be pushed to the official repo sometime after the launch of FFXIV 6.2

The /nekocfg command and the configuration menu was only added in version 1.1.0 which you can (for now) only download by adding `https://raw.githubusercontent.com/Meisterlala/NekoFans/master/repo.json` as a custom repository in the experimental settings.

If the description of the plugin in the plugin installer contains the sentence: `Multiple Image APIs are supported, allowing you to look at Catboys, Waifus, Cats, Dogs and more`, then you have version 1.1.0.
If you don't see that and the plugin description also doesn't show you the /nekocfg command under the /neko command then you still have version 1.0.7

**Comment by Fissie96** [comment]
Ah, that's definitely what I have, which is odd because I did add the repo before I installed it. Guess I'll wait till it's pushed to the official repo. Thank you!
