### ISSUE TITLE
Im Big super dumb, plz help me install nsfw portion. 

### ISSUE THREAD

**Issue by GloriousHunt** [Meisterlala/NekoLife#5]
So i found this add on today and was reading and saw nsfw as part of the optional installations. I read on how to install and add it but it no make sense to me so if i could have it even more simplified or even a video on how to add it, would be super duper awesome. im talking like this so you understand that i am not smart at unzipping and adding folders and files. if u need to msg me somehow, well i think you can get ahold of me. I just want the nsfw part added, ty.

**Comment by Meisterlala** [comment]
The installation instruction were a bit outdated. I updated them now. I also recorded a short Video on how to install the NSFW plugin. 
![optimized_1100](https://user-images.githubusercontent.com/6453306/191007157-03a338fb-69a4-4610-9ff8-76accffe5059.gif)

I hope this helps to make the installation process more easy to understand. If you still have questions or problems installing it feel free to ask.
