### ISSUE TITLE
[Bug Report] Unable to Install the NSFW patch

### ISSUE THREAD

**Issue by werewolfboy13** [Meisterlala/NekoLife#9]
I am receiving an error when installing the NSFW plugin. 

![image](https://user-images.githubusercontent.com/43587009/212440279-3186730a-2109-426a-b0b4-89337c7278a2.png)

**Comment by Meisterlala** [comment]
This was caused by the .Net 7 update somehow breaking the plugin. I released a new version (1.0.3) and it should be fixed now
